FROM jupyter/datascience-notebook

RUN echo "install.packages('lattice',repos = 'https://cran.rstudio.com')" | R --no-save
RUN echo "install.packages('latticeExtra',repos = 'https://cran.rstudio.com')" | R --no-save
RUN echo "install.packages('MEMSS',repos = 'https://cran.rstudio.com')" | R --no-save
RUN echo "install.packages('mlmRev',repos = 'https://cran.rstudio.com')" | R --no-save
RUN echo "install.packages('hexbin',repos = 'https://cran.rstudio.com')" | R --no-save
RUN echo "install.packages('maps',repos = 'https://cran.rstudio.com')" | R --no-save
RUN echo "install.packages('locfit',repos = 'https://cran.rstudio.com')" | R --no-save
RUN echo "install.packages('copula',repos = 'https://cran.rstudio.com')" | R --no-save
RUN echo "install.packages('RColorBrewer',repos = 'https://cran.rstudio.com')" | R --no-save
RUN echo "install.packages('MASS',repos = 'https://cran.rstudio.com')" | R --no-save
